# Form implementation generated from reading ui file 'rulesWin.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog1(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(726, 562)
        self.heading_lbl = QtWidgets.QLabel(Dialog)
        self.heading_lbl.setGeometry(QtCore.QRect(10, 0, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.heading_lbl.setFont(font)
        self.heading_lbl.setObjectName("heading_lbl")
        self.rules_lbl = QtWidgets.QLabel(Dialog)
        self.rules_lbl.setGeometry(QtCore.QRect(10, 30, 710, 421))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rules_lbl.setFont(font)
        self.rules_lbl.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.rules_lbl.setWordWrap(True)
        self.rules_lbl.setObjectName("rules_lbl")
        self.heading_lbl_2 = QtWidgets.QLabel(Dialog)
        self.heading_lbl_2.setGeometry(QtCore.QRect(10, 410, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.heading_lbl_2.setFont(font)
        self.heading_lbl_2.setObjectName("heading_lbl_2")
        self.rules_lbl_2 = QtWidgets.QLabel(Dialog)
        self.rules_lbl_2.setGeometry(QtCore.QRect(10, 440, 710, 111))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rules_lbl_2.setFont(font)
        self.rules_lbl_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.rules_lbl_2.setWordWrap(True)
        self.rules_lbl_2.setObjectName("rules_lbl_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "6 Nimmt! Rules"))
        self.heading_lbl.setText(_translate("Dialog", "Rules"))
        self.rules_lbl.setText(_translate("Dialog", "The aim of the game is to be the player with the lowest score. There is a deck of cards that range from 1 - 104. The game is played over several rounds with 10 turns each. In each turn all players will choose a card simultaneously, then the cards will be placed on the table in ascending order based on the following rules:\n"
"\n"
"The card must go on the row where the right most card is lower than the played card.\n"
"\n"
"If there are multiple rows with lower cards, the card goes on the row where the right most card is closest to the played card.\n"
"\n"
"If the row where the card goes contains 5 cards (The 6th card is being placed), the player placing the card takes all the cards in that row and puts them into their pickups, the card they placed then becomes the first card in that row.\n"
"\n"
"If there is no row with the right most card lower than the card being placed, the player placing the card chooses a row to take into their pickups with the card they placed becoming the new first card of that row."))
        self.heading_lbl_2.setText(_translate("Dialog", "End of round"))
        self.rules_lbl_2.setText(_translate("Dialog", "At the end of the round, each player scores the amount of bullheads in their pickup pile. Then if a player has at least 66 points, the game is over and the person with the lowest amount of points wins. Otherwise the cards are reshuffled and redealt to the player\'s hands and another round is played."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog1()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
