# Form implementation generated from reading ui file '.\ui-files\rulesWin.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(726, 562)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\ui-files\\../background/icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Dialog.setWindowIcon(icon)
        self.heading_lbl = QtWidgets.QLabel(Dialog)
        self.heading_lbl.setGeometry(QtCore.QRect(20, 10, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.heading_lbl.setFont(font)
        self.heading_lbl.setObjectName("heading_lbl")
        self.pg0_heading1 = QtWidgets.QLabel(Dialog)
        self.pg0_heading1.setGeometry(QtCore.QRect(20, 40, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.pg0_heading1.setFont(font)
        self.pg0_heading1.setObjectName("pg0_heading1")
        self.pg0_rules1 = QtWidgets.QLabel(Dialog)
        self.pg0_rules1.setGeometry(QtCore.QRect(20, 70, 681, 111))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pg0_rules1.setFont(font)
        self.pg0_rules1.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.pg0_rules1.setWordWrap(True)
        self.pg0_rules1.setObjectName("pg0_rules1")
        self.pg0_rules2 = QtWidgets.QLabel(Dialog)
        self.pg0_rules2.setGeometry(QtCore.QRect(20, 220, 681, 301))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pg0_rules2.setFont(font)
        self.pg0_rules2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.pg0_rules2.setWordWrap(True)
        self.pg0_rules2.setObjectName("pg0_rules2")
        self.pg0_heading2 = QtWidgets.QLabel(Dialog)
        self.pg0_heading2.setGeometry(QtCore.QRect(20, 190, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.pg0_heading2.setFont(font)
        self.pg0_heading2.setObjectName("pg0_heading2")
        self.right_btn = QtWidgets.QPushButton(Dialog)
        self.right_btn.setGeometry(QtCore.QRect(660, 510, 51, 41))
        self.right_btn.setObjectName("right_btn")
        self.left_btn = QtWidgets.QPushButton(Dialog)
        self.left_btn.setGeometry(QtCore.QRect(20, 510, 51, 41))
        self.left_btn.setObjectName("left_btn")
        self.pg1_heading1 = QtWidgets.QLabel(Dialog)
        self.pg1_heading1.setGeometry(QtCore.QRect(20, 40, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.pg1_heading1.setFont(font)
        self.pg1_heading1.setObjectName("pg1_heading1")
        self.pg1_rules1 = QtWidgets.QLabel(Dialog)
        self.pg1_rules1.setGeometry(QtCore.QRect(20, 70, 681, 161))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pg1_rules1.setFont(font)
        self.pg1_rules1.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.pg1_rules1.setWordWrap(True)
        self.pg1_rules1.setObjectName("pg1_rules1")
        self.pg1_rules2 = QtWidgets.QLabel(Dialog)
        self.pg1_rules2.setGeometry(QtCore.QRect(20, 260, 681, 161))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pg1_rules2.setFont(font)
        self.pg1_rules2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.pg1_rules2.setWordWrap(True)
        self.pg1_rules2.setObjectName("pg1_rules2")
        self.pg1_heading2 = QtWidgets.QLabel(Dialog)
        self.pg1_heading2.setGeometry(QtCore.QRect(20, 230, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.pg1_heading2.setFont(font)
        self.pg1_heading2.setObjectName("pg1_heading2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "6 Nimmt! Rules"))
        self.heading_lbl.setText(_translate("Dialog", "Rules"))
        self.pg0_heading1.setText(_translate("Dialog", "Goal"))
        self.pg0_rules1.setText(_translate("Dialog", "The goal of the game is to be the player with the fewest points. Points are scored by picking up rows of cards.\n"
"\n"
"There is a deck of cards ranging from 1-104. 10 cards are dealt to each player, and 4 are placed on the table in a vertical line to start the rows"))
        self.pg0_rules2.setText(_translate("Dialog", "Each turn, players will simultaneously pick a card to play to the table. Once every player has picked a card, the cards are uncovered and played in ascending order according to the following rules:\n"
"\n"
"1. The card must be put on a row where the last card in that row is lower than the played card\n"
"2.The card must be placed on the row where the last card in that row is closest to the played card\n"
"3.If the row the card goes on already has 5 cards in it (the played card is the 6th card in the row) the player picks up all the cards in the row, then the card being played becomes the new starting card for that row\n"
"4.If there are no rows where the last card is lower than the card being played, the player playing the card chooses a row to pick up, then the card being played becomes the new starting card for that row."))
        self.pg0_heading2.setText(_translate("Dialog", "Gameplay"))
        self.right_btn.setText(_translate("Dialog", ">"))
        self.left_btn.setText(_translate("Dialog", "<"))
        self.pg1_heading1.setText(_translate("Dialog", "End of the round"))
        self.pg1_rules1.setText(_translate("Dialog", "Once each player has played all 10 cards, the round ends and points are scored. Each player scores a point for each bullhead (the asterisks at the top of the cards) in their pick up pile. Remember you want to avoid scoring points. Once the points have been scored, the game ends if any player has reached the amount of points required to end the game (by default this is 66 it is configurable in settings). If no player has reached the amount of points required to end the game, another round begins. Rounds are played until any player has reached the amount of points required to end the game."))
        self.pg1_rules2.setText(_translate("Dialog", "Once a player has reached the amount of points required to end the game, the player with the fewest points wins. In case of a tie, the players share the victory."))
        self.pg1_heading2.setText(_translate("Dialog", "End of the game"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
